name: AutoBuild JDCLOUD-RE-CP-02 Kernel4.4 Padavan

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to compile'
        options:
        - JDCLOUD-RE-CP-02

      firmwarever:
        description: 'firmware''s version'
        required: true
        default: '20230324'

      uploadwet:
        type: boolean
        description: 'upload firmware to wetransfer'
        required: false
        default: 'false'

      upload_release:
        type: boolean
        description: 'upload firmware to RELEASE'
        required: true
        default: 'false'
env:
  REPOSITORY_URL: https://github.com/lu-1991/padavan-4.4-luban.git
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/linux-4.4-v1.0/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/padavan-4.4
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_DATEPREFIX: $(date +"%Y%m%d")
  FIRMWARE_AUTHOR: lu
  FIRMWARE_PATH: /opt/firmwares
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH/toolchain-mipsel
        mkdir -p toolchain-4.4.x
        wget $TOOLCHAIN_URL
        tar -xf mipsel-linux-uclibc.tar.xz -C toolchain-4.4.x
        
    - name: Custom config
      run: |
        cd $WORK_PATH/trunk
        if [ ! -f configs/templates/${{ github.event.inputs.target }}.config ] ; then
        echo "configs/templates/${{ github.event.inputs.target }}.config not found"
        exit 1
        fi
        cp -f configs/templates/${{ github.event.inputs.target }}.config .config
        ################################################################################################
        #å› ä¸åŒåž‹å·é…ç½®åŠŸèƒ½ä¸ä¸€æ ·ï¼Œæ‰€ä»¥å…ˆæŠŠé…ç½®é¡¹åˆ é™¤ï¼Œå¦‚æžœä½ è‡ªå·±è¦æ·»åŠ å…¶ä»–çš„ï¼Œä¹Ÿè¦å†™ä¸Šåˆ é™¤è¿™ä¸€æ¡ï¼Œåˆ‡è®°ï¼ï¼ï¼
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN   
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #åˆ é™¤é…ç½®é¡¹SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #åˆ é™¤é…ç½®é¡¹SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #åˆ é™¤é…ç½®é¡¹DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #åˆ é™¤é…ç½®é¡¹tunsafe
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #åˆ é™¤é…ç½®é¡¹é˜¿é‡ŒDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config #åˆ é™¤é…ç½®é¡¹srelay
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config #åˆ é™¤é…ç½®é¡¹adguardhome
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #åˆ é™¤é…ç½®é¡¹zerotier
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DDNSTO/d' .config #åˆ é™¤é…ç½®é¡¹ddnsto
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config #åˆ é™¤é…ç½®é¡¹wireguard
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALDRIVER/d' .config #åˆ é™¤é…ç½®é¡¹é˜¿é‡Œäº‘ç›˜
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config #åˆ é™¤é…ç½®é¡¹smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SQM/d' .config #åˆ é™¤é…ç½®é¡¹sqm
        #ä¸‹è½½åŠŸèƒ½
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #åˆ é™¤é…ç½®é¡¹aria
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config #åˆ é™¤é…ç½®é¡¹ariaç½‘é¡µæŽ§åˆ¶å°
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config #åˆ é™¤é…ç½®é¡¹TRANSMISSION
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config #åˆ é™¤é…ç½®é¡¹TRANSMISSIONç½‘é¡µæŽ§åˆ¶å°
        #æ ¡å›­ç½‘ç›¸å…³å¼€å§‹
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #åˆ é™¤é…ç½®é¡¹MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        #æ ¡å›­ç½‘ç›¸å…³ç»“æŸ
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #ä»¥ä¸‹é€‰é¡¹æ˜¯å®šä¹‰ä½ éœ€è¦çš„åŠŸèƒ½ï¼ˆy=é›†æˆ,n=å¿½ç•¥ï¼‰ï¼Œé‡æ–°å†™å…¥åˆ°.configæ–‡ä»¶
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #å¯ä»¥ä¸é›†æˆ
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=n" >> .config #é›†æˆxrayæ‰§è¡Œæ–‡ä»¶  ~4.5M
        echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config #ddnsto  ~0.5M
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config  #é˜¿é‡Œäº‘ç›˜  ~3m
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfsæ··æ·†æ’ä»¶
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #å†…ç½‘ç©¿é€FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #å†…ç½‘ç©¿é€FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #é˜¿é‡ŒDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdnsäºŒè¿›åˆ¶æ–‡ä»¶
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #é›†æˆv2rayæ‰§è¡Œæ–‡ä»¶ï¼ˆ3.8Må·¦å³)ï¼Œå¦‚æžœä¸é›†æˆï¼Œä¼šä»Žç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #é›†æˆtrojanæ‰§è¡Œæ–‡ä»¶(1.1Må·¦å³)ï¼Œå¦‚æžœä¸é›†æˆï¼Œä¼šä»Žç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KPå¹¿å‘Šè¿‡æ»¤
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=y" >> .config #åœ¨çº¿æ–‡ä»¶ç®¡ç†æœåŠ¡
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #é›†æˆcadduæ‰§è¡Œæ–‡ä»¶ï¼Œæ­¤æ–‡ä»¶æœ‰13M,è¯·æ³¨æ„å›ºä»¶å¤§å°ã€‚å¦‚æžœä¸é›†æˆï¼Œä¼šä»Žç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #å¯ä»¥ä¸é›†æˆ
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #ç½‘æ˜“äº‘è§£é”
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #ç½‘æ˜“äº‘è§£é”GOç‰ˆæœ¬æ‰§è¡Œæ–‡ä»¶ï¼ˆ4Må¤šï¼‰æ³¨æ„å›ºä»¶è¶…å¤§å°,ä¸é›†æˆä¼šè‡ªåŠ¨ä¸‹è½½
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        #########################################################################################
        #è‡ªå®šä¹‰æ·»åŠ å…¶å®ƒåŠŸèƒ½è¯·å‚è€ƒæºç configs/templates/ç›®å½•ä¸‹çš„configæ–‡ä»¶ã€‚æŒ‰ç…§ä¸Šé¢çš„æ ¼å¼æ·»åŠ å³å¯
        #æ ¼å¼å¦‚ä¸‹ï¼š
        #sed -i '/è‡ªå®šä¹‰é¡¹/d' .config
        #echo "è‡ªå®šä¹‰é¡¹=y" >> .config
        sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${{ github.event.inputs.firmwarever }}/g" ./versions.inc
        echo 'æ›´æ–°ç‰ˆæœ¬å·æ—¶é—´'
        #########################################################################################
    - name: Build firmware
      run: |
        cd $WORK_PATH/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify ${{ github.event.inputs.target }} 0
        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
        
    - name: Organize firmware files
      id: organize
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $WORK_PATH/trunk/images
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_DATEPREFIX}"_"${FIRMWARE_AUTHOR}"_"${{ github.event.inputs.target }}"_kernel4.4.trx"
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success'
      with:
        name: Padavan4.4-${{ github.event.inputs.target }}
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to WeTransfer
      if: steps.organize.outputs.status == 'success' && github.event.inputs.uploadwet == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "url=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
     
    - name: Generate release tag
      id: tag
      if: steps.organize.outputs.status == 'success' && github.event.inputs.upload_release == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")-Padavan4.4-${{ github.event.inputs.target }}" >> $GITHUB_OUTPUT
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "ðŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "ðŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 4
    
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: github.event.inputs.upload_release == 'true' && !cancelled()
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove obsolete firmwares on artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      if: steps.organizer.outputs.status == 'success'
      with:
        age: '1 day'
        skip-recent: 5
